import { test } from "@playwright/test";

test("test", async ({ page }) => {
  await page.goto("https://www.saucedemo.com/");
  await page.locator('[data-test="username"]').click();
  await page.locator('[data-test="username"]').fill("standard_user");
  await page.locator('[data-test="password"]').click();
  await page.locator('[data-test="password"]').fill("secret_saice");
  await page.locator('[data-test="login-button"]').click();
  await page.locator('[data-test="error-button"]').click();
  await page.locator('[data-test="password"]').click();
  await page.locator('[data-test="password"]').fill("secret_sauce");
  await page.locator('[data-test="login-button"]').click();
  await page.getByRole("button", { name: "Open Menu" }).click();
  await page.getByRole("button", { name: "Close Menu" }).click();
  // await page.getByRole("button", { name: "Open Menu" }).click();
  // await page.locator('[data-test="inventory-sidebar-link"]').click();
  // await page.locator('[data-test="about-sidebar-link"]').click();
  await page.getByRole("button", { name: "Open Menu" }).click();
  await page.locator('[data-test="reset-sidebar-link"]').click();
  await page.getByRole("button", { name: "Close Menu" }).click();
  await page.locator('[data-test="shopping-cart-link"]').click();
  await page.locator('[data-test="checkout"]').click();
  await page.locator('[data-test="firstName"]').click();
  await page.locator('[data-test="firstName"]').fill("aa");
  await page.locator('[data-test="lastName"]').click();
  await page.locator('[data-test="lastName"]').click();
  await page.locator('[data-test="lastName"]').fill("s");
  await page.locator('[data-test="postalCode"]').click();
  await page.locator('[data-test="postalCode"]').fill("93720");
  await page.locator('[data-test="continue"]').click();
  await page.locator('[data-test="cart-desc-label"]').click();
  await page.locator('[data-test="cart-desc-label"]').click();
  await page.locator('[data-test="cart-quantity-label"]').click();
  await page.locator('[data-test="shipping-info-label"]').click();
  await page.locator('[data-test="finish"]').click();
  await page.locator('[data-test="back-to-products"]').click();
  await page.locator('[data-test="product-sort-container"]').selectOption("za");
  await page.getByText("Name (Z to A)Name (A to Z)").click();
  await page.locator('[data-test="product-sort-container"]').selectOption("az");
  await page.getByText("Name (A to Z)Name (A to Z)").click();
  await page
    .locator('[data-test="product-sort-container"]')
    .selectOption("lohi");
  await page.getByText("Price (low to high)Name (A to").click();
  await page
    .locator('[data-test="product-sort-container"]')
    .selectOption("hilo");
  await page.getByText("Price (high to low)Name (A to").click();
  await page.locator('[data-test="product-sort-container"]').selectOption("az");
  await page.getByText("carry.allTheThings() with the").click();
  await page.locator('[data-test="item-4-img-link"]').click();
  await page.locator('[data-test="add-to-cart"]').click();
  await page.locator('[data-test="remove"]').click();
  await page.locator('[data-test="add-to-cart"]').click();
  await page.locator('[data-test="back-to-products"]').click();
  await page.locator('[data-test="add-to-cart-sauce-labs-onesie"]').click();
  await page.locator('[data-test="remove-sauce-labs-onesie"]').click();
  await page.locator('[data-test="add-to-cart-sauce-labs-onesie"]').click();
  await page
    .locator('[data-test="add-to-cart-sauce-labs-bolt-t-shirt"]')
    .click();
  await page.locator('[data-test="item-0-img-link"]').click();
  await page.locator('[data-test="add-to-cart"]').click();
  await page.locator('[data-test="back-to-products"]').click();
  await page.locator('[data-test="shopping-cart-link"]').click();
  await page.locator('[data-test="remove-sauce-labs-onesie"]').click();
  await page.locator('[data-test="checkout"]').click();
  await page.locator('[data-test="firstName"]').click();
  await page.locator('[data-test="firstName"]').fill("ss");
  await page.locator('[data-test="lastName"]').click();
  await page.locator('[data-test="lastName"]').fill("s");
  await page.locator('[data-test="lastName"]').click();
  await page.locator('[data-test="postalCode"]').click();
  await page.locator('[data-test="postalCode"]').fill("93720");
  await page.locator('[data-test="continue"]').click();
  await page.locator('[data-test="item-quantity"]').first().click();
  await page.locator('[data-test="item-quantity"]').first().dblclick();
  await page.locator('[data-test="item-quantity"]').first().click();
  await page.locator('[data-test="item-quantity"]').first().click();
  await page.locator('[data-test="item-quantity"]').first().click();
  await page.locator('[data-test="item-quantity"]').first().click();
  await page.getByText("Sauce Labs Bolt T-ShirtGet").click();
  await page.locator('[data-test="finish"]').click();
  await page.locator('[data-test="back-to-products"]').click();
  // const page1Promise = page.waitForEvent("popup");
  // await page.locator('[data-test="social-twitter"]').click();
  // const page1 = await page1Promise;
  // const page2Promise = page.waitForEvent("popup");
  // await page.locator('[data-test="social-facebook"]').click();
  // const page2 = await page2Promise;
  // const page3Promise = page.waitForEvent("popup");
  // await page.locator('[data-test="social-linkedin"]').click();
  // const page3 = await page3Promise;
  // await page.locator('[data-test="footer-copy"]').click();
  await page.locator("div").filter({ hasText: "Swag Labs" }).nth(5).click();
  await page.getByRole("button", { name: "Open Menu" }).click();
  await page.getByRole("button", { name: "Close Menu" }).click();
  await page.locator('[data-test="shopping-cart-link"]').click();
  await page.locator('[data-test="remove-sauce-labs-backpack"]').click();
  await page.locator('[data-test="checkout"]').click();
  await page.locator('[data-test="firstName"]').click();
  await page.locator('[data-test="firstName"]').fill("e");
  await page.locator('[data-test="lastName"]').click();
  await page.locator('[data-test="lastName"]').fill("e");
  await page.locator('[data-test="postalCode"]').click();
  await page.locator('[data-test="postalCode"]').fill("93720");
  await page.locator('[data-test="continue"]').click();
  await page.locator('[data-test="cancel"]').click();
  await page.locator('[data-test="add-to-cart-sauce-labs-backpack"]').click();
  await page.locator('[data-test="shopping-cart-link"]').click();
  await page.locator('[data-test="checkout"]').click();
  await page.locator('[data-test="continue"]').click();
  await page.locator("path").first().click();
  await page.locator('[data-test="firstName"]').fill("aa");
  await page.locator('[data-test="lastName"]').click();
  await page.locator('[data-test="lastName"]').fill("3");
  await page.locator('[data-test="continue"]').click();
  await page.locator('[data-test="postalCode"]').click();
  await page.locator('[data-test="postalCode"]').fill("2");
  await page.locator('[data-test="continue"]').click();
  await page.locator('[data-test="item-4-title-link"]').click();
  await page.locator('[data-test="back-to-products"]').click();
  await page.locator('[data-test="shopping-cart-link"]').click();
  await page.locator('[data-test="checkout"]').click();
  await page.locator('[data-test="firstName"]').click();
  await page.locator('[data-test="firstName"]').fill("1");
  await page.locator("form").click();
  await page.locator('[data-test="lastName"]').click();
  await page.locator('[data-test="lastName"]').fill("1");
  await page.locator('[data-test="lastName"]').click();
  await page.locator('[data-test="postalCode"]').click();
  await page.locator('[data-test="postalCode"]').fill("93720");
  await page.locator('[data-test="continue"]').click();
  await page.locator('[data-test="finish"]').click();
  await page.locator('[data-test="back-to-products"]').click();
  await page
    .locator('[data-test="add-to-cart-sauce-labs-bolt-t-shirt"]')
    .click();
  await page.locator('[data-test="remove-sauce-labs-bolt-t-shirt"]').click();
  await page
    .locator('[data-test="add-to-cart-sauce-labs-bolt-t-shirt"]')
    .click();
  await page.locator('[data-test="shopping-cart-link"]').click();
  await page.locator('[data-test="checkout"]').click();
  await page.locator('[data-test="postalCode"]').click();
  await page.locator('[data-test="postalCode"]').fill("aaaaa");
  await page.locator('[data-test="firstName"]').click();
  await page.locator('[data-test="postalCode"]').fill("aaaaae");
  await page.locator('[data-test="firstName"]').fill("w");
  await page.locator('[data-test="firstName"]').click();
  await page.locator('[data-test="firstName"]').fill("ww");
  await page.locator('[data-test="lastName"]').click();
  await page.locator('[data-test="lastName"]').click();
  await page.locator('[data-test="lastName"]').fill("w");
  await page.locator("form").click();
  await page.locator('[data-test="continue"]').click();
  await page.locator('[data-test="finish"]').click();
  await page.locator('[data-test="back-to-products"]').click();
  await page.locator('[data-test="add-to-cart-sauce-labs-bike-light"]').click();
  await page.locator('[data-test="shopping-cart-link"]').click();
  await page.locator('[data-test="checkout"]').click();
  await page.locator('[data-test="firstName"]').click();
  await page.locator('[data-test="postalCode"]').click();
  await page.locator('[data-test="postalCode"]').fill("-1");
  await page.locator('[data-test="firstName"]').click();
  await page.locator('[data-test="firstName"]').fill("###");
  await page.locator('[data-test="lastName"]').click();
  await page.locator('[data-test="lastName"]').fill("s");
  await page.locator('[data-test="continue"]').click();
  await page.locator('[data-test="finish"]').click();
  await page.locator('[data-test="back-to-products"]').click();
});
